name: SteveZ
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9838618054054677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e98a0c'
    - '#024d38'
    - '#fcfcfc'
    - '#da1525'
  brandStrength: 1
  lightness: 0.6167663729283959
  saturation: 0.45239895186387
  rhythmicContrast: 0.8078693114221096
purpose: []
